# Main configuration for the training process
paths:
  project_root: '/home/mikolaj/Desktop/Projects/my_projects/football-ai'
  train:
    images: '${paths.project_root}/data/train/images'
    annotations: '${paths.project_root}/data/train/coco_annotations/annotations.json'
  valid:
    images: '${paths.project_root}/data/valid/images'
    annotations: '${paths.project_root}/data/valid/coco_annotations/annotations.json'

training:
  num_epochs: 40
  batch_size: 8
  train_set_ratio: null  # If null then use full dataset
  valid_set_ratio: null  # If null then use full dataset
  frequency_validating: 60
  score_threshold: 0.3  # For evaluator
  save_checkpoints: true
  checkpoint_dir_path: null          # If save_checkpoints = True
  max_checkpoints: 5                 # If save_checkpoints = True
  frequency_saving_checkpoint: 60    # If save_checkpoints = True
  log_metrics: true
  map_per_class: true  # If log_metrics = True
  shuffle: true
  desire_bbox_format: xywh
  augmentation: true
  pin_memory: true
  device: 'cuda'

# Model configuration
model:
  model_id: PekingU/rtdetr_v2_r18vd
  id2label:
    0: 'Ball'
    1: 'Goalkeeper'
    2: 'Player'
    3: 'Referee'
  device: ${training.device}
  reset_head: true

# Optimizer configuration
optimizer:
  type: adamw  # Default
  params:
    lr: 5e-5
    backbone_lr: 5e-6
    weight_decay: 0.01

# Scheduler configuration
scheduler:
  type: null  # If you don't want to use scheduler the set the type as null
  params:
    T_max: ${training.num_epochs}
    eta_min: 1e-6
  
wandb_logger:
  project_name: football-ai